a = input('digite algo aqui:')
print('esse valor é do tipo primitivo:',type(a))
print('só tem espaços?',a.isspace())
print('é um numero ?',a.isnumeric())
print('É alfábetico?',a.isalpha())
print('É alfanumerico?',a.isalnum())
print('está em maiusculas/',a.isupper())
print('está em minusculas?',a.islower())
print('está capitalizada?',a.istitle())
